<template>
    <div>
        <PageHeader
            :pageTitle="displayBill.title"
            :pageSubtitle="billTypeLabel"
            :pageDate="displayBill.introducedDate"
            :colour="displayBill.headerColour ?? undefined"
        />
        <NuxtPage :bill="displayBill" :originalBill="bill" :status="status" :error="error" :refresh="refresh" />
    </div>
</template>

<script setup lang="ts">
// this was generated by cursor ... I will tidy it up later (I don't know why it has decided to abstract the bill model into a displayBill object)
const config = useRuntimeConfig()
const apiBase = config.public.apiBase
const route = useRoute()

const READING_VOTES_DISCLAIMER =
    'Only reading votes are shown here; these votes determine whether the Bill progresses through Parliament. Other votes, such as votes on whether to amend parts of the Bill, can be seen in Hansard.'

const PROCEDURAL_URGENCY = {
    title: 'Urgency used',
    description:
        'This bill was progressed through one or more stages using urgency. Urgency allows the Government to fast-track the legislative process by extending the sitting hours of the House of Representatives and skipping the select committee stage of a bill, and allows bills to pass through more than one stage per sitting day.',
    link: {
        label: 'Learn more about urgency',
        url: 'https://www.parliament.nz/en/visit-and-learn/how-parliament-works/laws-and-bills/what-happens-to-a-bill/',
    },
}

const PROCEDURAL_EXTENDED_SITTINGS = {
    title: 'Extended sittings used',
    description:
        'This bill was progressed during one or more extended sittings of the House of Representatives. This enables MPs to meet for longer than normal to consider legislation. It allows bills to pass through more than one stage per sitting day.',
    link: {
        label: 'Learn more about extended sittings',
        url: 'https://www.parliament.nz/en/visit-and-learn/how-parliament-works/parliamentary-business/house-sitting-patterns/',
    },
}

const billKey = computed(() => `bill-${route.params.id}`)
const { data: bill, status, error, refresh } = await useAsyncData(
    billKey,
    () => $fetch(`${apiBase}bills/${route.params.id}/`),
)

const apiJsonUrl = computed(() => `${apiBase}bills/${route.params.id}/`)

const formatDateLabel = (value?: string) => {
    if (!value) return ''
    const parsed = new Date(value)
    if (Number.isNaN(parsed.getTime())) return ''
    return new Intl.DateTimeFormat('en-NZ', { dateStyle: 'long' }).format(parsed)
}

const formatDateTimeLabel = (value?: string) => {
    if (!value) return ''
    const parsed = new Date(value)
    if (Number.isNaN(parsed.getTime())) return ''
    try {
        return new Intl.DateTimeFormat('en-NZ', {
            dateStyle: 'long',
            timeStyle: 'short',
        }).format(parsed)
    } catch {
        return parsed.toLocaleString('en-NZ')
    }
}

const votingMethodLookup: Record<string, { label: string; description: string }> = {
    party: {
        label: 'Party voting',
        description: 'Parties decided whether or not to support this bill and cast votes on behalf of all their MPs.',
    },
    personal: {
        label: 'Personal voting',
        description: 'Each MP cast their own vote on this bill.',
    },
    mixed: {
        label: 'Mixed voting',
        description: 'Both personal and party voting were used at different stages of this bill.',
    },
}

const displayBill = computed(() => {
    const data = bill.value && typeof bill.value === 'object' ? (bill.value as Record<string, unknown>) : {}
    const hasApiData = Object.keys(data).length > 0

    if (!hasApiData) {
        const pending = status.value === 'pending'
        return {
            title: pending ? 'Loading…' : 'Bill',
            type: '',
            introducedDate: '',
            headerColour: null as string | null,
            summary: '',
            status: 'unknown',
            statusSummary: '',
            resources: {
                json: {
                    label: 'JSON',
                    url: apiJsonUrl.value,
                },
            },
            votingMethod: null,
            proceduralNotes: [],
            members: [],
            first_reading_date: null,
            second_reading_date: null,
            third_reading_date: null,
            defeated_date: null,
            defeated_reading: null,
            vote_stubs: [],
            votes: [],
            votesNote: READING_VOTES_DISCLAIMER,
            lastSynced: '',
        }
    }

    const people = Array.isArray(data.people_responsible) ? data.people_responsible : []
    const members = (people as Record<string, unknown>[]).map((person) => {
        const name =
            (person.display_name as string | undefined) ??
            [person.first_name, person.last_name].filter(Boolean).join(' ')
        const photo = person.photo as { file?: string } | string | undefined
        const avatarUrl =
            typeof photo === 'object' && photo?.file
                ? photo.file
                : typeof photo === 'string'
                  ? photo
                  : '/images/generic-profile-picture.png'
        return {
            id: person.id ?? name,
            slug: person.slug ?? '',
            name: name || 'Member details unavailable',
            role: (person.cached_description as string) ?? '',
            colour: person.cached_colour ?? null,
            avatarUrl,
            link: person.slug ? `/people/${person.slug}` : '',
        }
    })

    const statusSummaryParts: string[] = []
    const now = new Date()
    const parseDate = (value?: string) => {
        if (!value) return null
        const parsed = value.length === 10 ? new Date(`${value}T00:00:00`) : new Date(value)
        return Number.isNaN(parsed.getTime()) ? null : parsed
    }
    const describeDate = (prefix: string, value?: string) => {
        const formatted = formatDateLabel(value)
        return formatted ? `${prefix} ${formatted}.` : ''
    }

    if (data.status === 'in_progress') {
        if (data.whole_house_date) {
            statusSummaryParts.push(
                describeDate(
                    'The Committee of the whole House concluded its consideration on',
                    data.whole_house_date as string,
                ),
            )
        } else if (data.second_reading_date) {
            statusSummaryParts.push(describeDate('This bill passed its second reading on', data.second_reading_date as string))
        } else if (data.first_reading_date) {
            statusSummaryParts.push(describeDate('This bill passed its first reading on', data.first_reading_date as string))
            if (data.report_back_date) {
                const reportBack = parseDate(data.report_back_date as string)
                if (reportBack) {
                    statusSummaryParts.push(
                        reportBack > now
                            ? describeDate('The Select Committee is due to report back on', data.report_back_date as string)
                            : describeDate('The Select Committee report was due back on', data.report_back_date as string),
                    )
                }
            }
            if (data.submissions_due_date) {
                const submissions = parseDate(data.submissions_due_date as string)
                if (submissions) {
                    statusSummaryParts.push(
                        submissions > now
                            ? describeDate('Public submissions are due on', data.submissions_due_date as string)
                            : describeDate('Public submissions were due on', data.submissions_due_date as string),
                    )
                }
            }
        } else if (data.introduction_date) {
            statusSummaryParts.push(describeDate('This bill was introduced on', data.introduction_date as string))
        }
    }

    if (statusSummaryParts.length === 0 && data.parliament_api_status) {
        statusSummaryParts.push(`Parliament status: ${data.parliament_api_status}.`)
    }
    if (data.select_committee_name) {
        const committeeStatus = data.select_committee_status ? ` (${data.select_committee_status})` : ''
        statusSummaryParts.push(`Select committee: ${data.select_committee_name}${committeeStatus}.`)
    }
    if (data.last_activity_date) {
        const lastActivity = formatDateLabel(data.last_activity_date as string)
        if (lastActivity) statusSummaryParts.push(`Last activity on ${lastActivity}.`)
    }

    const proceduralNotes = []
    if (data.urgency_used) {
        proceduralNotes.push(PROCEDURAL_URGENCY)
    }
    if (data.extended_sittings_used) {
        proceduralNotes.push(PROCEDURAL_EXTENDED_SITTINGS)
    }

    const vm = data.voting_methods as string | undefined
    const votingMethod =
        vm && votingMethodLookup[vm]
            ? votingMethodLookup[vm]
            : vm
              ? {
                    label: String(vm).replace(/_/g, ' '),
                    description: 'Voting method reported by Parliament.',
                }
              : null

    const billTextUrl = typeof data.legislation_url === 'string' ? data.legislation_url.trim() : ''
    const actUrl =
        data.act_number && data.act_year
            ? `https://legislation.govt.nz/act/results.aspx?search=ad_act___${data.act_year}_${data.act_number}__25_ac@bn@rn@dn@apub@aloc@apri@apro@aimp@bgov@bloc@bpri@bmem@rpub@rimp_ac@ainf@anif@aaif@aase@arep@bcur@rinf@rnif_a_aw_se_&p=1`
            : ''
    const parliamentUrl = data.parliament_api_id
        ? `https://bills.parliament.nz/v/6/${data.parliament_api_id}`
        : typeof data.parliament_document_id === 'string' && data.parliament_document_id
          ? `https://www.parliament.nz/en/pb/bills-and-laws/bills-proposed-laws/document/${data.parliament_document_id}`
          : ''

    const syncedAt = formatDateTimeLabel(data.retrieved_at as string | undefined)

    return {
        title: (data.name ?? data.title ?? '') as string,
        type: (data.bill_type ?? data.type ?? '') as string,
        introducedDate: (data.introduction_date ?? data.introduced_date ?? '') as string,
        headerColour: null as string | null,
        summary: (data.description ?? data.summary ?? '') as string,
        status: (data.status ?? 'unknown') as string,
        statusSummary: statusSummaryParts.join(' ') || '',
        resources: {
            billText: billTextUrl
                ? {
                      label: data.name ? `${data.name} (legislation.govt.nz)` : 'Bill text (legislation.govt.nz)',
                      url: billTextUrl,
                  }
                : null,
            actText: actUrl
                ? {
                      label: data.act_name ? `${data.act_name} (legislation.govt.nz)` : 'Act text (legislation.govt.nz)',
                      url: actUrl,
                  }
                : null,
            parliament: parliamentUrl
                ? {
                      label: 'View on Parliament website',
                      url: parliamentUrl,
                  }
                : null,
            json: {
                label: 'JSON',
                url: apiJsonUrl.value,
            },
        },
        votingMethod: votingMethod ?? null,
        proceduralNotes,
        members,
        first_reading_date: data.first_reading_date ?? null,
        second_reading_date: data.second_reading_date ?? null,
        third_reading_date: data.third_reading_date ?? null,
        defeated_date: data.defeated_date ?? null,
        defeated_reading:
            data.defeated_reading !== undefined && data.defeated_reading !== null
                ? Number(data.defeated_reading)
                : null,
        vote_stubs: Array.isArray(data.vote_stubs) ? data.vote_stubs : [],
        votes: [],
        votesNote: READING_VOTES_DISCLAIMER,
        lastSynced: syncedAt ? `Bill details last synced on ${syncedAt}.` : '',
    }
})

const billTypeLabel = computed(() => {
    const types = config.public.valueKeys?.billTypes ?? {}
    const typeKey = displayBill.value.type
    if (!typeKey) return ''
    return (types as Record<string, { description?: string }>)[typeKey]?.description ?? String(typeKey)
})

usePageSeo({
    title: () => displayBill.value.title,
    description: () => {
        const summary = displayBill.value.summary?.trim()
        if (summary) return summary
        const statusSummary = displayBill.value.statusSummary?.trim()
        if (statusSummary) return statusSummary
        const type = billTypeLabel.value
        return type ? `${type} before Parliament.` : undefined
    },
})
</script>
